# Generated by Django 6.0.6 on 2026-07-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('college', models.CharField(max_length=30, null=True)),
                ('join_date', models.DateField(null=True)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=30)),
                ('paid_fees', models.DecimalField(decimal_places=2, max_digits=30)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('tech', models.CharField(max_length=30, null=True)),
                ('img', models.FileField(upload_to='student/images/')),
            ],
        ),
    ]
