# Generated by Django 6.0.6 on 2026-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='left_fees',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
