# Generated by Django 6.0.6 on 2026-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_left_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.FileField(upload_to='images/'),
        ),
    ]
