# Generated by Django 6.0.6 on 2026-07-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_city_student_password_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='img',
            new_name='image',
        ),
    ]
